config/routes.rb
Rails.application.routes.draw do

  resources :posts, only: [:index, :show] do
    resources :comments, only: [:index, :create]
  end

  resources :users, except: [:index, :create, :new, :show] do
    resources :posts
  end

  devise_for :users, path: 'auth'
  root 'posts#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments

  validates :title, presence: true
  validates :content, presence: true, length: {minimum: 250}
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @posts = Post.all.order(created_at: :desc)
  end

  def show
    @post = Post.find params[:id]
    @users = User.all
    @comment = Comment.new
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new safe_params
    @post.user = current_user
    if @post.save
      flash[:success] = "Post successfully created"
      redirect_to user_posts_path
    else
      render :new
    end
  end

  def update
    @post = Post.find params[:id]
    if @post.update safe_params
      flash[:success] = "Post successfully updated"
      redirect_to user_posts_path
    else
      render :edit
    end
  end

  def destroy
    del_post = Post.find params[:id]
    del_coms = Comment.where("post_id = ?", params[:id])
    del_coms.each do |comment|
      comment.destroy
    end
    del_post.destroy
    flash[:success] = "Post successfully deleted"
    redirect_to user_posts_path
  end

  def edit
    @post = Post.find params[:id]
  end

  protected
  def safe_params
      params.require(:post).permit(:title, :content)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_edit_post_form.html.erb
<div class="new-edit-post-area">
<h1>Edit Post</h1>

<%= form_for @post, :url => user_post_path(current_user, @post) do |f| %>
  <%= f.label :title, "Title" %> <br>
  <%= f.text_field :title, class: "form-control" %> <br>
  <%= f.label :title, "Content" %> <br>
  <%= f.text_area :content, size: "60x5", class: "form-control txtarea txtarea-edit-new" %> <br>
  <%= f.submit "Editar", class: "btn btn-primary"  %>
<% end %>
</div>

app/views/posts/_new_post_form.html.erb
<div class="new-edit-post-area">
<h1>New Post</h1>

<%= form_for @post, url: user_posts_path(current_user) do |f| %>
  <%= f.label :title, "Title" %> <br>
  <%= f.text_field :title, class: "form-control" %> <br>
  <%= f.label :title, "Content" %> <br>
  <%= f.text_area :content, size: "60x5", class: "form-control txtarea txtarea-edit-new" %> <br>
  <%= f.submit "Crear", class: "btn btn-primary"  %>
<% end %>
</div>

app/views/posts/edit.html.erb
<% if !@post.errors.messages.empty?%>
  <% @post.errors.full_messages.each do |error| %>
    <p1><%= error %> </p1> <br>
  <%end%>
<% end %>
<%= link_to "Back", user_posts_path(current_user), class:"back-link-50"%>
<%= render 'edit_post_form' %>

app/views/posts/index.html.erb
<% flash.each do |name, msg| -%>
<div class="alert alert-success alert-dismissible" role="alert">
  <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= msg %>
</div>
<% end %>
<div class="flex-container">
  <%if @posts.empty?%>
    <h2>There are no posts yet</h2>
  <%else%>
    <%@posts.each do |post|%>
      <div class="post-container">
        <%=link_to post_path(post.id) do%>
          <h2><%= post.title %></h2>
        <% end %>
        <h5>Publicado por <span><%=post.user.email%></span> hace aproximadamente <%=time_ago_in_words(post.created_at)%> </h5>
        <%if post.content.length > 250 %> <!-- Se puede quitar cuando se ponga la validacion-->
          <p><%= markdown(post.content[0..250] + '...') %></p>
        <%else%><!-- Se puede quitar cuando se ponga la validacion-->
          <p><%= markdown(post.content) %></p> <!-- Se puede quitar cuando se ponga la validacion-->
        <% end %><!-- Se puede quitar cuando se ponga la validacion-->
        <% if post.user == current_user %>
          <%= link_to "<span class='glyphicon glyphicon-pencil'><span>".html_safe,  edit_user_post_path(current_user, post.id) %>
          <%= link_to "<span class='glyphicon glyphicon-trash'><span>".html_safe, user_post_path(current_user, post),:data => {:confirm => "You sure?",:method => "delete"} %>
        <%end%>
      </div>
    <%end%>
  <%end%>
</div>
<script type="text/javascript">
  $('.close').click(function(){
    $('.alert').fadeOut(300)
  })
</script>

app/views/posts/new.html.erb
<div class="errors">
<% if !@post.errors.messages.empty?%>
  <% @post.errors.full_messages.each do |error| %>
    <p1><%= error %> </p1> <br>
  <%end%>
<% end %>
</div>
<%= link_to "Back", user_posts_path(current_user), class:"back-link-50"%>
<%= render 'new_post_form' %>

app/views/posts/show.html.erb
    <div class="flex-container">
      <% if user_signed_in? %>
        <%= link_to "Back", user_posts_path(current_user), class:"back-link"%>
      <%else%>
        <%= link_to "Back", posts_path, class:"back-link"%>
      <%end%>
      <div class="post-container">
        <h2><%= @post.title %> </h2>
        <p><%= markdown(@post.content) %></p>
        <h5><span><%= @post.user.email %> </span></h5>
        <% if @post.user == current_user %>
          <%= link_to "<span class='glyphicon glyphicon-pencil'><span>".html_safe,  edit_user_post_path(current_user, @post.id) %>
          <%= link_to "<span class='glyphicon glyphicon-trash'><span>".html_safe, user_post_path(current_user, @post),:data => {:confirm => "You sure?",:method => "delete"} %>
        <%end%>
      </div>
      <div class="comments-area">
        <h2>Comments</h2>
        <% if @post.comments.empty? %>
        <p>There are no comments yet</p>
        <% end %>
        <div class="comments-container">
        </div>

    <%if user_signed_in?%>
    <%= form_for [@post, @comment], class:"new-comment" do |f| %>
    <%=f.text_area :content, size: "60x3", class:"form-control txtarea"%>
    <%=f.submit "Comment", :disable_with => 'Creating...', class: "btn btn-primary actions" %>
    <% end %>
    <% end %>
    </div>
  </div>
    <script type="text/javascript">
    $(document).on('turbolinks:load', function(){
      loadComments()
    })
    function loadComments(){
      $.ajax({
        method: "GET",
        contentType: 'application/json',
        url: "<%= post_comments_path @post %>"
      }).done(function(data, status, xhr){
        drawComments(data)
      }).fail(function(xhr, satus, error){
        alert('Algo salio mal con el request ajax')
      })
    }

    function drawComments(data){
      var commentsToAdd = ''
      data.forEach(function(comment){
        commentsToAdd += '<div class="comment-container"><h5><span>' + comment.user.email + '</span> comentó el <span>' + parseDate(comment.created_at) + '</span></h5><p>' + comment.content + '</p></div>'
      })
      $('.comments-container').html(commentsToAdd)
    }

    function parseDate(createdAt) {
      return createdAt.replace(/\w\d\d\D\d\d\D\d\d\D\d\d\d\w/, '')
    }
    </script>