config/routes.rb
Rails.application.routes.draw do

  resources :posts, only: [:index, :show] do
    resources :comments, only: [:index, :create]
  end

  resources :users, except: [:index, :create, :new, :show] do
    resources :posts
  end

  devise_for :users, path: 'auth'
  root 'posts#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SuperBlog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if user_signed_in? %>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <%= link_to "Super-Blog", user_posts_path(current_user) %>
        </div>
        <div class="collapse navbar-collapse" id="right-menu">
          <ul class="nav navbar-nav navbar-left">
            <li style="padding-left: 30px; left: 905px;"><%= link_to "Sign out", destroy_user_session_path, method: 'delete'%></li>
            <li style="left: 905px;"><%= link_to "New Post", new_user_post_path(current_user) %></li>
          </ul>
        </div>
      </div>
    </nav>
    <%else%>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <%= link_to "Super-Blog", posts_path %>
        </div>
        <div class="collapse navbar-collapse" id="right-menu">
          <ul class="nav navbar-nav navbar-left">
            <li style="padding-left: 30px; left: 930px;"><%= link_to "Sign up", new_user_registration_path%></li>
            <li style="left: 930px;"><%= link_to "Sign in", user_session_path%> </li>
          </ul>
        </div>
      </div>
    </nav>
    <%end%>
    <%= yield %>
  </body>
</html>